Week2
Lidemy/mentor-program-5th-rockyooooooo pull request #4
Opened 2021-04-16 04:48 UTC by rockyooooooo

hw6 寫到快眼花了，現在換助教眼花了 XD

2021-04-17 12:21 UTC, rockyooooooo commented
挑戰題我看到就馬上想到要試試二分搜尋法
在我的電腦上面跑沒問題，放到 LIOJ 上面就會是 Wrong Answer，不知道哪裡出問題...
所以直接用了內建的 indexOf() 來做這題，速度好像也比題目的那個函式快0.0，但二元搜尋還是比較快就是了

超級挑戰題我也是看到題目就想到全加器，但是實在想不到怎麼寫 code 來實作，
所以用遞迴來試試看，沒想到成功了（？）

超級超級挑戰題花了我一天一夜的時間，邊想邊查資料邊理解，終於完成了
這題我也是一開始的方向就對了，覺得只能一個位數一個位數慢慢乘，
但最難的就是怎麼實作阿~~~~
完全想不到該怎麼做，所以直接找答案了
找到答案還是看了一天才看懂，難怪我當初資工系念得不好 QQ

2021-04-18 04:59 UTC, cwc329 commented
> **挑戰題**我看到就馬上想到要試試二分搜尋法
> 在我的電腦上面跑沒問題，放到 LIOJ 上面就會是 Wrong Answer，不知道哪裡出問題...
> 所以直接用了內建的 indexOf() 來做這題，速度好像也比題目的那個函式快0.0，但二元搜尋還是比較快就是了
LIOJ 是透過閱讀輸出判斷答案，所以要印出而不是回傳。

2021-04-18 05:35 UTC, cwc329 requested changes
hw6 修正一下，如果要完整呈現的話最好真的從頭開始說明，或者只要說明 function 內怎麼運作就好。
挑戰題有一題沒有完成，不過比較沒有大礙，反正是挑戰題。

2021-04-18 05:35 UTC, cwc329 commented on homeworks/week2/hw1.js
> +printStars(0);
為何要 call function？

2021-04-18 05:35 UTC, cwc329 commented on homeworks/week2/hw1.js
> +      i < 10 ? console.log(i, " *") : console.log(i, "*");
為什麼這邊要這樣寫？有什麼原因嗎？

2021-04-18 05:35 UTC, cwc329 commented on homeworks/week2/hw6.md
> +1. 執行第 12 行，呼叫 isValid 函式，傳入一個 Array 型態的參數，value 為 3, 5, 8, 13, 22, 35。
怎麼會直接執行第 12 行，還呼叫一個沒有被宣告的函示？

2021-04-18 05:35 UTC, cwc329 commented on homeworks/week2/super-challenge.js
> +console.log(add(5, 3));
試試看 (12, 45) 這組。

2021-04-18 05:35 UTC, cwc329 commented on homeworks/week2/challenge.js
> +// lines[n + 1] ~ lines[n + m]  -> 待查詢的數字
給個提示：資料型態

2021-04-18 05:35 UTC, cwc329 commented on homeworks/week2/super-super-challenge.js
> +);
成功！
GJ

2021-04-18 05:47 UTC, rockyooooooo commented on homeworks/week2/hw1.js
> +printStars(0);
call function 才能印出星星

2021-04-18 05:49 UTC, rockyooooooo commented on homeworks/week2/hw1.js
> +      i < 10 ? console.log(i, " *") : console.log(i, "*");
先印出 i 是為了方便計算，i 是個位數的時候多印一個空白，單純排版好看 XD

2021-04-18 06:08 UTC, rockyooooooo commented on homeworks/week2/super-challenge.js
> +console.log(add(5, 3));
在我電腦測試結果：111001，應該正確？0.0

2021-04-18 06:19 UTC, cwc329 commented on homeworks/week2/hw1.js
> +      i < 10 ? console.log(i, " *") : console.log(i, "*");
多一個空白並不符合需求，
而且題目也沒有要先印出數字，
下次可以的話請看清楚需求。

2021-04-18 06:20 UTC, cwc329 commented on homeworks/week2/super-challenge.js
> +console.log(add(5, 3));
看一下題目要求輸出什麼

2021-04-18 07:10 UTC, rockyooooooo commented on homeworks/week2/hw1.js
> +      i < 10 ? console.log(i, " *") : console.log(i, "*");
了解，已改善

2021-04-18 07:10 UTC, rockyooooooo commented on homeworks/week2/hw6.md
> +1. 執行第 12 行，呼叫 isValid 函式，傳入一個 Array 型態的參數，value 為 3, 5, 8, 13, 22, 35。
已補上宣告函式步驟

2021-04-18 07:11 UTC, rockyooooooo commented on homeworks/week2/super-challenge.js
> +console.log(add(5, 3));
已改成輸出十進位數字

2021-04-18 07:12 UTC, rockyooooooo commented on homeworks/week2/challenge.js
> +// lines[n + 1] ~ lines[n + m]  -> 待查詢的數字
原來是型態的部分！終於解決了！感謝助教！

2021-04-18 07:24 UTC, cwc329 approved these changes
超級挑戰題依舊沒有達成需求，但是基本題都可以了。
我先 merge，之後有修改可以再發 PR 再交一次作業。

2021-04-18 07:24 UTC, cwc329 commented on homeworks/week2/super-challenge.js
> +console.log(parseInt(add(12, 45), 2))
`add` 本身還是沒有達到要求，回傳的值依舊不是題目要求的。

2021-04-18 07:24 UTC, merged